name: Deploy to Azure Web App
 
on:

  push:

    branches:

      - main
 
jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v3
 
    - name: Set up Node.js

      uses: actions/setup-node@v3

      with:

        node-version: '16'
 
    - name: Install dependencies

      run: npm install
 
    - name: Zip the app

      run: zip -r app.zip .
 
    - name: Deploy to Azure Web App

      uses: azure/webapps-deploy@v2

      with:

        app-name: demo-webapp-ci-cd

        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

 
